name: appmap-analysis

# Define the event that triggers the workflow
on:
  pull_request:
  push:
    branches:
      - main # Change this to the name of the mainline branch
  schedule:
    - cron: '0 0 * * 0'

# Define the jobs
jobs:
  test:
    # Specify the type of runner
    runs-on: ubuntu-latest

    # Define the steps for the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install AppMap tools
        id: install-appmap
        uses: getappmap/install-action@v1
        with:
          project-type: pipenv

      - name: Run tests
        run: |
          pytest tests/

      - name: Save AppMaps
        uses: actions/cache/save@v3
        if: always()
        with:
          path: ${{ steps.install-appmap.outputs.appmap-dir }}
          key: appmaps-${{ github.sha }}-${{ github.run_attempt }}

  appmap-analysis:
    if: always()
    needs: [test] # You may need to change this to match the name of the step that runs your tests.
    uses: getappmap/analyze-action/.github/workflows/appmap-analysis.yml@v1
    permissions:
      actions: read
      contents: read
      checks: write
      pull-requests: write