name: CI

# Define the event that triggers the workflow
on: 
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

# Define the jobs
jobs:
  test:
    # Specify the type of runner
    runs-on: ubuntu-latest

    # Define the steps for the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/