name: CI

# Define the event that triggers the workflow
on: 
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

# Define the jobs
jobs:
  test:
    # Specify the type of runner
    runs-on: ubuntu-latest

    # Define the steps for the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/

      - name: Save AppMaps
        uses: actions/cache/save@v3
        if: always()
        with:
          path: ./tmp/appmap
          key: appmaps-${{ github.sha }}-${{ github.run_attempt }}
          
  appmap-analysis:
    if: always()
    needs: [ test ]
    uses: getappmap/analyze-action/.github/workflows/appmap-analysis.yml@v1
    permissions:
      actions: read
      contents: read
      checks: write
      pull-requests: write